In [1]:
import numpy as np
import pandas as pd

## Create a 2D array and print the dim and shape

In [8]:
a=np.array([[9,8,7,6,5,4],[3,6,7,8,9,4]])
a

array([[9, 8, 7, 6, 5, 4],
       [3, 6, 7, 8, 9, 4]])

In [9]:
a.ndim

2

In [10]:
a.shape

(2, 6)

## Create an array of 20 numbers using arange function and slice the values between 10 to 15

In [12]:
b=np.array(range(20))
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [13]:
b[10:15]

array([10, 11, 12, 13, 14])

## Create 2 arrays of 7X5 dimension and broadcast between the 2 arrays using

In [18]:
x=np.array([[9,8,7,6,5],[3,6,7,8,9],[1,2,3,4,5],[8,7,5,6,2,],[0,3,5,6,7],[1,4,5,7,8],[9,7,8,5,4]])
x

array([[9, 8, 7, 6, 5],
       [3, 6, 7, 8, 9],
       [1, 2, 3, 4, 5],
       [8, 7, 5, 6, 2],
       [0, 3, 5, 6, 7],
       [1, 4, 5, 7, 8],
       [9, 7, 8, 5, 4]])

In [15]:
y=np.array([[1,2,3,4,5],[6,7,8,9,1],[7,4,1,2,3],[9,6,3,2,1],[1,5,2,6,8],[1,8,7,9,2],[2,4,5,6,8]])
y

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 1],
       [7, 4, 1, 2, 3],
       [9, 6, 3, 2, 1],
       [1, 5, 2, 6, 8],
       [1, 8, 7, 9, 2],
       [2, 4, 5, 6, 8]])

In [19]:
x+y

array([[10, 10, 10, 10, 10],
       [ 9, 13, 15, 17, 10],
       [ 8,  6,  4,  6,  8],
       [17, 13,  8,  8,  3],
       [ 1,  8,  7, 12, 15],
       [ 2, 12, 12, 16, 10],
       [11, 11, 13, 11, 12]])

In [20]:
x-y

array([[ 8,  6,  4,  2,  0],
       [-3, -1, -1, -1,  8],
       [-6, -2,  2,  2,  2],
       [-1,  1,  2,  4,  1],
       [-1, -2,  3,  0, -1],
       [ 0, -4, -2, -2,  6],
       [ 7,  3,  3, -1, -4]])

In [21]:
x*y

array([[ 9, 16, 21, 24, 25],
       [18, 42, 56, 72,  9],
       [ 7,  8,  3,  8, 15],
       [72, 42, 15, 12,  2],
       [ 0, 15, 10, 36, 56],
       [ 1, 32, 35, 63, 16],
       [18, 28, 40, 30, 32]])

In [22]:
x/y

array([[9.        , 4.        , 2.33333333, 1.5       , 1.        ],
       [0.5       , 0.85714286, 0.875     , 0.88888889, 9.        ],
       [0.14285714, 0.5       , 3.        , 2.        , 1.66666667],
       [0.88888889, 1.16666667, 1.66666667, 3.        , 2.        ],
       [0.        , 0.6       , 2.5       , 1.        , 0.875     ],
       [1.        , 0.5       , 0.71428571, 0.77777778, 4.        ],
       [4.5       , 1.75      , 1.6       , 0.83333333, 0.5       ]])

## Create 2 incompatible arrays for broadcast and print out the error

In [23]:
g=np.array([1,4,5,6,5])
h=np.array([1,2,3,4])
g+h

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

## Create two arrays of any dimension and perform vstack and hstack

In [27]:
d=np.array([[4,3,2],[2,1,1]])
e=np.array([[1,2,3],[3,2,1]])

In [28]:
np.vstack((d,e))

array([[4, 3, 2],
       [2, 1, 1],
       [1, 2, 3],
       [3, 2, 1]])

In [29]:
np.hstack((d,e))

array([[4, 3, 2, 1, 2, 3],
       [2, 1, 1, 3, 2, 1]])

## Append two arrays using axis = 0 and axis = 1

In [31]:
d

array([[4, 3, 2],
       [2, 1, 1]])

In [37]:
np.append(d,[[8,9,7]],axis=0)

array([[4, 3, 2],
       [2, 1, 1],
       [8, 9, 7]])

In [44]:
np.append(d,[[8,9,7],[3,2,1]],axis=1)

array([[4, 3, 2, 8, 9, 7],
       [2, 1, 1, 3, 2, 1]])

## Create a dataframe for 8 X 4 dimension using list of lists and name the columns while dataframe creation

In [45]:
list1=[['Madhu',4,20,80],['Geetha',2,25,50],['Vino',1,28,70],['tamizh',3,25,90],['santhan',6,24,60],['aswin',5,26,90],['vicki',7,28,80],['Guna',8,26,30]]

In [47]:
a=pd.DataFrame(list1,columns=['name','r.no','age','score'])

In [48]:
a

name  r.no  age  score
0    Madhu     4   20     80
1   Geetha     2   25     50
2     Vino     1   28     70
3   tamizh     3   25     90
4  santhan     6   24     60
5    aswin     5   26     90
6    vicki     7   28     80
7     Guna     8   26     30

## Create a dataframe of 4 X 8 dimension using a dictionary

In [54]:
x=pd.DataFrame({'name':['madhu','geetha','ram','seetha'],
  'r.no':[1,2,3,4],
  'age':[15,16,14,13],
   'section':['a','b','c','d'],
  'score':[70,80,90,100],
   'physics':[60,40,50,30],
   'chemistry':[30,40,50,60],
   'maths':[100,90,50,90]
  })
x

name  r.no  age section  score  physics  chemistry  maths
0   madhu     1   15       a     70       60         30    100
1  geetha     2   16       b     80       40         40     90
2     ram     3   14       c     90       50         50     50
3  seetha     4   13       d    100       30         60     90

## Use loc and iloc to subset the data for the above dataframe

In [57]:
x.loc[:3,['name','score']]

name  score
0   madhu     70
1  geetha     80
2     ram     90
3  seetha    100

In [58]:
x.iloc[:2,:5]

name  r.no  age section  score
0   madhu     1   15       a     70
1  geetha     2   16       b     80

## How to check the total number of not null values in a column?

In [60]:
x['name'].notnull().sum()

4

## Create a dataframe with missing values and fill them all with 100

In [86]:
list1=[['Madhu',4,28,80],['Geetha',2,np.nan,50],['Vino',7,28,70],['tamizh',3,25],['santhan',np.nan,24,60],['aswin',5,26],['vicki',7,np.nan,80],['Guna',np.nan,26,30]]

In [87]:
a=pd.DataFrame(list1,columns=['name','r.no','age','score'])

In [88]:
a

name  r.no   age  score
0    Madhu   4.0  28.0   80.0
1   Geetha   2.0   NaN   50.0
2     Vino   7.0  28.0   70.0
3   tamizh   3.0  25.0    NaN
4  santhan   NaN  24.0   60.0
5    aswin   5.0  26.0    NaN
6    vicki   7.0   NaN   80.0
7     Guna   NaN  26.0   30.0

In [89]:
a.fillna(100)

name   r.no    age  score
0    Madhu    4.0   28.0   80.0
1   Geetha    2.0  100.0   50.0
2     Vino    7.0   28.0   70.0
3   tamizh    3.0   25.0  100.0
4  santhan  100.0   24.0   60.0
5    aswin    5.0   26.0  100.0
6    vicki    7.0  100.0   80.0
7     Guna  100.0   26.0   30.0

## Create a dataframe with missing values and drop the null records

In [91]:
b=pd.DataFrame(list1,columns=['name','r.no','age','score'])

In [92]:
b

name  r.no   age  score
0    Madhu   4.0  28.0   80.0
1   Geetha   2.0   NaN   50.0
2     Vino   7.0  28.0   70.0
3   tamizh   3.0  25.0    NaN
4  santhan   NaN  24.0   60.0
5    aswin   5.0  26.0    NaN
6    vicki   7.0   NaN   80.0
7     Guna   NaN  26.0   30.0

In [94]:
b.dropna()

name  r.no   age  score
0  Madhu   4.0  28.0   80.0
2   Vino   7.0  28.0   70.0

## Aggregation -- Get the average age group by Region

In [106]:
dict1={'age':[25,30,45,35,33,35,25,52,21,24,48,22,27,28,21,51,23],
       'hair color':['black','black','red','blond','brown','brown','black','brown','blond','blond','black','black','brown','black','blond','black','brown'],
       'u.s region':['Southwest','Northwest','Northeast','Southwest','Southwest','Northeast','Southwest','Southeast','Southwest','Northeast','Southwest','Southwest','Northeast','Southeast','Southeast','Northwest','Southeast'],
        'validation':[1,1,1,0,0,0,0,0,1,0,1,0,0,1,1,0,1]}

In [107]:
x=pd.DataFrame(dict1)


In [8]:
x

age hair color u.s region  validation
0    25      black  Southwest           1
1    30      black  Northwest           1
2    45        red  Northeast           1
3    35      blond  Southwest           0
4    33      brown  Southwest           0
5    35      brown  Northeast           0
6    25      black  Southwest           0
7    52      brown  Southeast           0
8    21      blond  Southwest           1
9    24      blond  Northeast           0
10   48      black  Southwest           1
11   22      black  Southwest           0
12   27      brown  Northeast           0
13   28      black  Southeast           1
14   21      blond  Southeast           1
15   51      black  Northwest           0
16   23      brown  Southeast           1

In [12]:
x.groupby(['u.s region'])['age'].mean()

u.s region
Northeast    32.750000
Northwest    40.500000
Southeast    31.000000
Southwest    29.857143
Name: age, dtype: float64

## Get the sum of Age and Validation group by Hair color and then reset the index

In [13]:
x.groupby(['hair color'])['age'].mean().reset_index()

hair color        age
0      black  32.714286
1      blond  25.250000
2      brown  34.000000
3        red  45.000000

##  Get the mean and the median of Age group by Region

In [15]:
x.groupby(['u.s region'])['age'].agg([np.mean,np.median])

mean  median
u.s region                   
Northeast   32.750000    31.0
Northwest   40.500000    40.5
Southeast   31.000000    25.5
Southwest   29.857143    25.0

## Split the below table into half and perform merge (inner, left and right) on Region. One example for each type of merge (inner, left and right)

In [16]:
dict2={'age':[25,30,45,35,33,35,25,52],
       'hair color':['black','black','red','blond','brown','brown','black','brown'],
       'u.s region':['Southwest','Northwest','Northeast','Southwest','Southwest','Northeast','Southwest','Southeast'],
        'validation':[1,1,1,0,0,0,0,0]}

In [17]:
dict3={'age':[21,24,48,22,27,28,21,51,23],
       'hair color':['blond','blond','black','black','brown','black','blond','black','brown'],
       'u.s region':['Southwest','Northeast','Southwest','Southwest','Northeast','Southeast','Southeast','Northwest','Southeast'],
        'validation':[1,0,1,0,0,1,1,0,1]}

In [19]:
xl=pd.DataFrame(dict2)
xr=pd.DataFrame(dict3)
xl

age hair color u.s region  validation
0   25      black  Southwest           1
1   30      black  Northwest           1
2   45        red  Northeast           1
3   35      blond  Southwest           0
4   33      brown  Southwest           0
5   35      brown  Northeast           0
6   25      black  Southwest           0
7   52      brown  Southeast           0

In [20]:
xr

age hair color u.s region  validation
0   21      blond  Southwest           1
1   24      blond  Northeast           0
2   48      black  Southwest           1
3   22      black  Southwest           0
4   27      brown  Northeast           0
5   28      black  Southeast           1
6   21      blond  Southeast           1
7   51      black  Northwest           0
8   23      brown  Southeast           1

In [30]:
z=xl.merge(xr,on='u.s region',how='inner')
z

age_x hair color_x u.s region  validation_x  age_y hair color_y  \
0      25        black  Southwest             1     21        blond   
1      25        black  Southwest             1     48        black   
2      25        black  Southwest             1     22        black   
3      35        blond  Southwest             0     21        blond   
4      35        blond  Southwest             0     48        black   
5      35        blond  Southwest             0     22        black   
6      33        brown  Southwest             0     21        blond   
7      33        brown  Southwest             0     48        black   
8      33        brown  Southwest             0     22        black   
9      25        black  Southwest             0     21        blond   
10     25        black  Southwest             0     48        black   
11     25        black  Southwest             0     22        black   
12     30        black  Northwest             1     51        black   
13     45          red  Northeast             1     24        blond   
14     45          red  Northeast             1     27        brown   
15     35        brown  Northeast             0     24        blond   
16     35        brown  Northeast             0     27        brown   
17     52        brown  Southeast             0     28        black   
18     52        brown  Southeast             0     21        blond   
19     52        brown  Southeast             0     23        brown   

    validation_y  
0              1  
1              1  
2              0  
3              1  
4              1  
5              0  
6              1  
7              1  
8              0  
9              1  
10             1  
11             0  
12             0  
13             0  
14             0  
15             0  
16             0  
17             1  
18             1  
19             1

In [32]:
a=xl.merge(xr,on='u.s region',how='left')
a

age_x hair color_x u.s region  validation_x  age_y hair color_y  \
0      25        black  Southwest             1     21        blond   
1      25        black  Southwest             1     48        black   
2      25        black  Southwest             1     22        black   
3      30        black  Northwest             1     51        black   
4      45          red  Northeast             1     24        blond   
5      45          red  Northeast             1     27        brown   
6      35        blond  Southwest             0     21        blond   
7      35        blond  Southwest             0     48        black   
8      35        blond  Southwest             0     22        black   
9      33        brown  Southwest             0     21        blond   
10     33        brown  Southwest             0     48        black   
11     33        brown  Southwest             0     22        black   
12     35        brown  Northeast             0     24        blond   
13     35        brown  Northeast             0     27        brown   
14     25        black  Southwest             0     21        blond   
15     25        black  Southwest             0     48        black   
16     25        black  Southwest             0     22        black   
17     52        brown  Southeast             0     28        black   
18     52        brown  Southeast             0     21        blond   
19     52        brown  Southeast             0     23        brown   

    validation_y  
0              1  
1              1  
2              0  
3              0  
4              0  
5              0  
6              1  
7              1  
8              0  
9              1  
10             1  
11             0  
12             0  
13             0  
14             1  
15             1  
16             0  
17             1  
18             1  
19             1

In [33]:
b=xl.merge(xr,on='u.s region',how='right')
b

age_x hair color_x u.s region  validation_x  age_y hair color_y  \
0      25        black  Southwest             1     21        blond   
1      35        blond  Southwest             0     21        blond   
2      33        brown  Southwest             0     21        blond   
3      25        black  Southwest             0     21        blond   
4      45          red  Northeast             1     24        blond   
5      35        brown  Northeast             0     24        blond   
6      25        black  Southwest             1     48        black   
7      35        blond  Southwest             0     48        black   
8      33        brown  Southwest             0     48        black   
9      25        black  Southwest             0     48        black   
10     25        black  Southwest             1     22        black   
11     35        blond  Southwest             0     22        black   
12     33        brown  Southwest             0     22        black   
13     25        black  Southwest             0     22        black   
14     45          red  Northeast             1     27        brown   
15     35        brown  Northeast             0     27        brown   
16     52        brown  Southeast             0     28        black   
17     52        brown  Southeast             0     21        blond   
18     30        black  Northwest             1     51        black   
19     52        brown  Southeast             0     23        brown   

    validation_y  
0              1  
1              1  
2              1  
3              1  
4              0  
5              0  
6              1  
7              1  
8              1  
9              1  
10             0  
11             0  
12             0  
13             0  
14             0  
15             0  
16             1  
17             1  
18             0  
19             1

## Split the below table and perform concat row wise and column wise

In [36]:
pd.concat([xl,xr],ignore_index="True") ## row wise

age hair color u.s region  validation
0    25      black  Southwest           1
1    30      black  Northwest           1
2    45        red  Northeast           1
3    35      blond  Southwest           0
4    33      brown  Southwest           0
5    35      brown  Northeast           0
6    25      black  Southwest           0
7    52      brown  Southeast           0
8    21      blond  Southwest           1
9    24      blond  Northeast           0
10   48      black  Southwest           1
11   22      black  Southwest           0
12   27      brown  Northeast           0
13   28      black  Southeast           1
14   21      blond  Southeast           1
15   51      black  Northwest           0
16   23      brown  Southeast           1

In [39]:
pd.concat([xl,xr],axis=1) ## column wise

age hair color u.s region  validation  age hair color u.s region  \
0  25.0      black  Southwest         1.0   21      blond  Southwest   
1  30.0      black  Northwest         1.0   24      blond  Northeast   
2  45.0        red  Northeast         1.0   48      black  Southwest   
3  35.0      blond  Southwest         0.0   22      black  Southwest   
4  33.0      brown  Southwest         0.0   27      brown  Northeast   
5  35.0      brown  Northeast         0.0   28      black  Southeast   
6  25.0      black  Southwest         0.0   21      blond  Southeast   
7  52.0      brown  Southeast         0.0   51      black  Northwest   
8   NaN        NaN        NaN         NaN   23      brown  Southeast   

   validation  
0           1  
1           0  
2           1  
3           0  
4           0  
5           1  
6           1  
7           0  
8           1